version: "3"
services:

  db:
    image: postgres:13.6
    restart: always
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    logging:
        driver: "json-file"
        options:
           max-size: "50m"
    volumes:
      - ./datadir/postgres-data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql.conf
  blockscout:
    depends_on:
      - db
    image: domecloud/blockscout-fix-int
    restart: always
    links:
      - db:database
    command: 'mix do ecto.create, ecto.migrate, phx.server'
    logging:
        driver: "json-file"
        options:
           max-size: "50m"
    env_file:
      -  ./envs/common-blockscout.env
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'geth'
        BLOCK_TRANSFORMER: 'base'
        ETHEREUM_JSONRPC_HTTP_URL: http://65.108.100.176:8545/
        DATABASE_URL: postgresql://postgres:@db:5432/blockscout?ssl=false
        ECTO_USE_SSL: 1
    ports:
      - 80:4000

